name: Build & Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: |
          cd src
          CGO_ENABLED=0 go build -o greeting
          pwd
          ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Greeting
          path: /home/runner/work/Greeting/Greeting

  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Get artifacts
        uses: actions/download-artifact@master
        with:
          name: Greeting
          path: /home/runner/work/Greeting/Greeting

      - name: Settings
        run: |
          chmod +x ./src/Greeting
          ls -l

      - name: Build & Publish to Registry
        uses: wuhan005/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          repository: ${{ secrets.DOCKER_REPO }}
          tag_format: "%YYYY%_%MM%_%DD%_%H%%m%%s%"
          auto_tag: true